# Wrangler configuration for Cloudflare Pages

name = "delovable"
compatibility_date = "2024-04-15"

# Build configuration
[build]
command = "npm run build:web"
upload.format = "directory"
output_dir = "dist/web"

# Environment variables
[vars]
NODE_VERSION = "18"

# Production environment
[env.production]
# Add production-specific variables here if needed
API_URL = "https://delovable-worker.neckolis.workers.dev"

# Preview/staging environment
[env.preview]
# Add preview-specific variables here if needed
API_URL = "https://delovable-worker-dev.neckolis.workers.dev"
