name = "delovable"
main = "src/index.ts"
compatibility_date = "2024-04-15"

# Configure R2 bucket for temporary storage
[[r2_buckets]]
binding = "DELOVABLE_BUCKET"
bucket_name = "delovable-temp"
preview_bucket_name = "delovable-temp-dev"

# Environment variables
[vars]
WORKER_ENV = "production"

# GitHub OAuth credentials (these are set in the Cloudflare dashboard)
# GITHUB_CLIENT_ID = "your-github-client-id"
# GITHUB_CLIENT_SECRET = "your-github-client-secret"

# Development environment
[env.development]
name = "delovable-dev"
[env.development.vars]
WORKER_ENV = "development"
# GITHUB_CLIENT_ID = "your-github-client-id"
# GITHUB_CLIENT_SECRET = "your-github-client-secret"

# Enable logs
[observability.logs]
enabled = true
